export * from "./landing/Landing"
export * from "./dashboard/Dashboard"
export * from "./progress/Progress"
export * from "./lvl1/Lvl1"
export * from "./python/Python"
export * from "./c/Clang"
// export * from "./cpp/Cpp"
export * from "./java/Java"
export * from "./lvlpy/Lvpy1"
export * from "./lvlc/Lvc1"
export * from "./lvlcpp/Lvcpp1"
export * from "./lvljava/Lvjava1"
export * from "./tictactoe/TttGame"
export * from "./lvl2/Lvl2"
